CREATE TABLE CUSTOMER(
    CNO NUMBER(3) NOT NULL,
    NAME VARCHAR2(10),
    PW VARCHAR2(12),
    EMAIL VARCHAR2(20),
    CONSTRAINT CUSTOMER_PK PRIMARY KEY(CNO),
    CONSTRAINT CUSTOMER_UQ UNIQUE (EMAIL),
    CONSTRAINT CHK_CNO CHECK (CNO>=0));
    
CREATE TABLE EBOOK(
    ISBN NUMBER(13) NOT NULL,
    TITLE VARCHAR2(100),
    PUBLISHER VARCHAR2(14),
    YEAR NUMBER(4),
    CNO NUMBER(3),
    EXT_TIMES NUMBER(1) CHECK (EXT_TIMES >= 0 AND EXT_TIMES <=2),
    DATE_RENTED DATE,
    DATE_DUE DATE,
    CONSTRAINT EBOOK_PK PRIMARY KEY(ISBN),
    CONSTRAINT EBOOK_FK FOREIGN KEY (CNO) REFERENCES CUSTOMER(CNO));
    
    
CREATE TABLE RESERVE(
    ISBN NUMBER(13) NOT NULL,
    CNO NUMBER(3) NOT NULL,
    DATE_TIME DATE,
    CONSTRAINT RESERVE_PK PRIMARY KEY (ISBN, CNO),
    CONSTRAINT RESERVE_FK1 FOREIGN KEY (ISBN) REFERENCES EBOOK(ISBN),
    CONSTRAINT RESERVE_FK2 FOREIGN KEY (CNO) REFERENCES CUSTOMER(CNO));
    
CREATE TABLE PREVIOUS_RENTAL(
    ISBN NUMBER(13) NOT NULL,
    DATE_RENTED DATE NOT NULL,
    DATE_RETURNED DATE NOT NULL,
    CNO NUMBER(3) NOT NULL,
    CONSTRAINT PREV_RENTAL_PK PRIMARY KEY(ISBN, DATE_RENTED),
    CONSTRAINT PREV_RENTAL_FK1 FOREIGN KEY (ISBN) REFERENCES EBOOK(ISBN),
    CONSTRAINT PREV_RENTAL_FK2 FOREIGN KEY (CNO) REFERENCES CUSTOMER(CNO));
    
CREATE TABLE AUTHORS(
    ISBN NUMBER(13) NOT NULL,
    AUTHOR VARCHAR2(14) NOT NULL,
    CONSTRAINT AUTHORS_PK PRIMARY KEY (ISBN, AUTHOR),
    CONSTRAINT AUTHORS_FK FOREIGN KEY (ISBN) REFERENCES EBOOK(ISBN));
    